const fs = require('fs');

let code = fs.readFileSync('src/services/chatAssistantService.ts', 'utf8');

// 1. Update extractEntities intent classification
const intentStart = code.indexOf('    // Intent Classifications');
const intentEnd = code.indexOf('    return {', intentStart);

if (intentStart === -1 || intentEnd === -1) {
  console.error('Could not locate intent block');
  process.exit(1);
}

const newIntentSection = [
  "    // Intent Classifications",
  "    let navigationTarget: ExtractedQueryEntities['navigationTarget'] = null;",
  "    if (/(show map|open map|view map|radar map|on map|radar view|open radar|வரைபடம்|வரைபடத்தில்|வரைபடம் திற|நக்ஷா|నక్షా|మ్యాప్)/i.test(qLower)) {",
  "      navigationTarget = 'map';",
  "    } else if (/(my gigs|my jobs|claimed jobs|my shifts|applied gigs|claimed shifts|என் வேலைகள்|என் பணிகள்|मेरी नौकरियां|నా పనులు)/i.test(qLower)) {",
  "      navigationTarget = 'my-gigs';",
  "    } else if (/(community demand|demand radar|district demand|demand trends|சமூக தேவை|டிமாண்ட் ராடார்|मांग रुझान|డిమాండ్ రాడార్)/i.test(qLower)) {",
  "      navigationTarget = 'community-demand';",
  "    }",
  "",
  "    const isOvertimeQueryIntent = /(overtime|extra hours|extra time|ot pay|கூடுதல் நேரம்|ஓவர் டைம்|ओटी|ఓవర్‌టైమ్)/i.test(qLower);",
  "    const isWageQueryIntent = (",
  "      /(wage|salary|daily pay|rate|how much.*earn|how much.*pay|fair pay|benchmark|pay rate|hourly pay|சம்பளம்|ஊதியம்|கூலி|வேதனம்|वेतन|मजदूरी|జీతం|వేతనం)/i.test(qLower) || isOvertimeQueryIntent",
  "    ) && !/(create|post|publish)/i.test(qLower);",
  "",
  "    const isGreeting = /^(hi|hello|hey|greetings|good\\s+(morning|afternoon|evening)|hola|namaste|vanakkam|namaskaram|வணக்கம்|ஹலோ|ஹாய்|నమస్కారం|హలో|नमस्ते|नमस्कार|हैलो)\\b/i.test(qLower) ||",
  "      ['hi', 'hello', 'hey', 'start'].includes(qLower);",
  "",
  "    const isPlatformAbout = /(what is talent2task|about talent2task|what does this app do|tell me about talent2task|என்ன தளம்|டேலண்ட்2டாஸ்க் என்றால் என்ன|टैलेंट2टास्क क्या है)/i.test(qLower);",
  "    ",
  "    const isPlatformMatchingHow = /(how does.*matching work|how is match.*calculated|how match.*work|explain matching|formula|பொருத்தம் எவ்வாறு|மேட்ச் ஸ்கோர் எப்படி|मैचिंग कैसे काम करती है)/i.test(qLower);",
  "",
  "    const isPostJobIntent = /(create a job|create.*job|create.*gig|post a job|post.*job|post a gig|post.*gig|post me a gig|post me gig|help me post|help me create|post gig|create gig|வேலை போஸ்ட்|வேலை உருவாக்க|வேலை அறிவிப்பு|ஆள் தேவை|ஜாப் போஸ்ட்|नौकरी पोस्ट|काम पोस्ट)/i.test(qLower);",
  "",
  "    const isHelp = (",
  "      /(who are you|what can you do|how to use|features|commands|guide|help\\b|help me\\b|உதவி|సహాయం|మదद)/i.test(qLower) &&",
  "      !detectedSkill &&",
  "      !isNearMe &&",
  "      !radiusKm &&",
  "      !availability &&",
  "      !isHighRating &&",
  "      !isPostJobIntent &&",
  "      !navigationTarget &&",
  "      !isWageQueryIntent",
  "    );",
  "",
  "    const isUnrelated = /(weather|temperature|joke|capital of|who won|president|movie|song|வானிலை|காலநிலை|मौसम|వాతావరణం)/i.test(qLower);",
  "",
  "    const isDestructiveIntent = /(delete|remove|cancel|நீக்கு|ரத்து|हटाएं|రद्द|తొలగించు|రద్దు)\\s*(?:my\\s*)?(job|gig|post|posting|account|listing|application|வேலை|பணி|कार्य|नौकरी|పని)/i.test(qLower) ||",
  "      /(delete job|delete gig|delete my post|remove job|cancel gig|cancel job)/i.test(qLower);",
  "",
  "    const isExplanationIntent = /(why was this|why recommended|why this worker|why this job|how match score|explain score|recommendation reason|ஏன் பரிந்துரைக்கப்பட்டது|ஏன் இந்த வேலை|எப்படி பொருத்தம்|क्यों अनुशंसित|ఎందుకు సిఫార్సు)/i.test(qLower);",
  "",
  "    const isSkillGapIntent = /(what should i learn|skills should i learn|skills to learn|what to learn|how to earn more|கற்க வேண்டும்|தேவைப்படும் திறன்|நேర్చుకోవాలి|कौशल सीखने)/i.test(qLower);",
  "",
  "    const isDemandIntent = /(in demand|demand in|trending skills|high demand|அதிக தேவை|டிமாண்ட்|कौशल मांग|డిమాండ్)/i.test(qLower);",
  "",
  "    const isWorkerSearchIntent = /(find.*worker|hire.*worker|need a worker|hire a|need.*candidate|top rated.*worker|highly rated.*worker|i need to hire|hire someone|need workers|find workers|ஆட்கள் தேவை|பணியாளர் தேவை|தொழிலாளர்கள்|కార్మికులు|कारीगर|श्रमिक)/i.test(qLower) ||",
  "      (isRecruiter && /(worker|candidates|plumbers|painters|electricians|drivers|cooks|helpers|carpenters|masons|rated|top|best)/i.test(qLower) && !/(find.*job|show.*jobs)/i.test(qLower));",
  "",
  "    const isJobSearchIntent = /(find.*job|show.*job|jobs near|jobs within|jobs match|matching my skills|available tomorrow|available today|shifts near|work near|gigs near|find gigs|near me gigs|show jobs|gigs|வேலை|பணி|பணிகள்|పని|ఉద్యోగం|नौकरी|काम)/i.test(qLower) ||",
  "      (isNearMe && !isWorkerSearchIntent && !isPostJobIntent) ||",
  "      (!isRecruiter && Boolean(detectedSkill) && !isPostJobIntent && !isWorkerSearchIntent);",
  "",
  "    const isAmbiguousSearch = /(find me a job|i need a job|i need work|show me work|find work|get a job|வேலை வேண்டும்|வேலை காட்டு|काम चाहिए|నాకు పని కావాలి)/i.test(qLower) && !detectedSkill;",
  ""
].join('\n');

code = code.slice(0, intentStart) + newIntentSection + '\n' + code.slice(intentEnd);

// 2. Insert navigation and wage query methods if not already there
const methodInsertMarker = '  private buildAmbiguousClarificationResponse';
if (!code.includes('buildWageQueryResponse')) {
  const newMethods = [
    "  private buildNavigationActionResponse(target: 'map' | 'my-gigs' | 'explore' | 'post-manage' | 'community-demand', lang: Language, timestamp: string): ChatMessage {",
    "    let reply = '';",
    "    const actions: ChatActionItem[] = [];",
    "",
    "    if (target === 'map') {",
    "      reply = lang === 'ta'",
    "        ? '🗺️ உங்கள் அருகிலுள்ள நேரலை வேலைகள் மற்றும் பணியாளர்களைக் காட்டும் ரேடார் வரைபடப் பார்வைக்கு மாற்றப்படுகிறது.'",
    "        : lang === 'hi'",
    "        ? '🗺️ आपके नजदीकी लाइव कार्यों और श्रमिकों को दिखाने वाले रडार मानचित्र दृश्य पर जाया जा रहा है।'",
    "        : lang === 'te'",
    "        ? '🗺️ మీ సమీపంలోని ప్రత్యక్ష పనులు మరియు కార్మికులను చూపే రాడార్ మ్యాప్ వీక్షణకు మార్చబడుతోంది.'",
    "        : '🗺️ Switching to the Radar Map view showing live gigs and verified candidates in your area.';",
    "      actions.push({",
    "        type: 'NAVIGATE_TAB',",
    "        label: lang === 'ta' ? 'வரைபடம் திற' : lang === 'hi' ? 'मानचित्र खोलें' : lang === 'te' ? 'మ్యాప్ తెరవండి' : 'Open Radar Map',",
    "        payload: { tab: 'explore', view: 'map' },",
    "        autoExecute: true",
    "      });",
    "    } else if (target === 'my-gigs') {",
    "      reply = lang === 'ta'",
    "        ? '📋 நீங்கள் ஏற்றுக்கொண்ட பணிகள் மற்றும் கடந்த கால ஷிப்ட் விவரங்களைக் காட்டும் \"என் வேலைகள்\" பக்கத்திற்குச் செல்கிறோம்.'",
    "        : lang === 'hi'",
    "        ? '📋 आपके द्वारा दावा किए गए कार्यों और शिफ्ट विवरणों को दिखाने वाले \"मेरे कार्य\" पृष्ठ पर जाया जा रहा है।'",
    "        : lang === 'te'",
    "        ? '📋 మీరు క్లెయిమ్ చేసిన పనులను చూపే \"నా పనులు\" ట్యాబ్‌కు మారుతున్నాము.'",
    "        : '📋 Navigating to your \"My Gigs\" dashboard showing active and completed shifts.';",
    "      actions.push({",
    "        type: 'NAVIGATE_TAB',",
    "        label: lang === 'ta' ? 'என் வேலைகள்' : lang === 'hi' ? 'मेरे कार्य' : lang === 'te' ? 'నా పనులు' : 'My Claimed Gigs',",
    "        payload: { tab: 'my-gigs' },",
    "        autoExecute: true",
    "      });",
    "    } else if (target === 'community-demand') {",
    "      reply = lang === 'ta'",
    "        ? '📊 மாவட்ட அளவிலான நேரலை திறன் தேவை நுண்ணறிவு மற்றும் சந்தை போக்குகள் திறக்கப்படுகிறது.'",
    "        : lang === 'hi'",
    "        ? '📊 जिला स्तरीय कौशल मांग और बाजार रुझान अंतर्दृष्टि खोली जा रही है।'",
    "        : lang === 'te'",
    "        ? '📊 జిల్లా స్థాయి నైపుణ్య డిమాండ్ మరియు మార్కెట్ ట్రెండ్స్ తెరవబడుతున్నాయి.'",
    "        : '📊 Opening District-level Skill Demand & Real-Time Market Intelligence.';",
    "      actions.push({",
    "        type: 'OPEN_COMMUNITY_DEMAND',",
    "        label: lang === 'ta' ? 'தேவை நுண்ணறிவு' : lang === 'hi' ? 'मांग विश्लेषण' : lang === 'te' ? 'డిమాండ్ అంతర్దృష్టి' : 'Demand Intelligence',",
    "        autoExecute: true",
    "      });",
    "    } else {",
    "      reply = lang === 'ta'",
    "        ? '🌐 அனைத்து உள்ளூர் வேலைகளையும் ஆராயும் பக்கத்திற்குச் செல்கிறோம்.'",
    "        : lang === 'hi'",
    "        ? '🌐 सभी स्थानीय कार्यों का पता लगाने के लिए पृष्ठ पर जाया जा रहा है।'",
    "        : lang === 'te'",
    "        ? '🌐 అన్ని స్థానిక పనులను అన్వేషించే పేజీకి మారుతున్నాము.'",
    "        : '🌐 Navigating to the Explore Gigs marketplace.';",
    "      actions.push({",
    "        type: 'NAVIGATE_TAB',",
    "        label: lang === 'ta' ? 'ஆராய்க' : lang === 'hi' ? 'अन्वेषण' : lang === 'te' ? 'అన్వేషించండి' : 'Explore Marketplace',",
    "        payload: { tab: 'explore', view: 'both' },",
    "        autoExecute: true",
    "      });",
    "    }",
    "",
    "    return {",
    "      id: 'msg_' + Date.now(),",
    "      sender: 'assistant',",
    "      text: reply,",
    "      timestamp,",
    "      actions,",
    "      intent: 'NAVIGATE_TAB'",
    "    };",
    "  }",
    "",
    "  private buildWageQueryResponse(query: string, context: ChatContextPayload, entities: ExtractedQueryEntities, timestamp: string): ChatMessage {",
    "    const lang = context.language;",
    "    const user = context.currentUser;",
    "    const city = entities.location || user?.city || 'Chennai';",
    "    const targetSkill = entities.skill || 'General';",
    "",
    "    const demandIntel = demandIntelligenceService.analyzeDemand(context.jobs, city);",
    "    const skillStat = demandIntel.skillsDemand.find(s => s.skill.toLowerCase().includes(targetSkill.toLowerCase()));",
    "",
    "    const avgHourly = skillStat?.avgHourlyPay || 180;",
    "    const baseDaily = avgHourly * 4;",
    "    const fullDaily = avgHourly * 8;",
    "    const masterDaily = Math.round(fullDaily * 1.35);",
    "",
    "    const otMatch = query.match(/(\\d+)\\s*(?:hours?|hrs?|மணி|घंटे|గంటలు)/i);",
    "    const payMatch = query.match(/(?:₹|rs\\.?|inr)?\\s*(\\d{3,5})/i);",
    "    const isOtQuery = entities.isOvertimeQueryIntent || /(overtime|extra hours|கூடுதல் நேரம்|ஓவர் டைம்|ओटी|ఓవర్‌టైమ్)/i.test(query);",
    "",
    "    let reply = '';",
    "    const actions: ChatActionItem[] = [];",
    "",
    "    if (isOtQuery && (otMatch || payMatch)) {",
    "      const totalHours = otMatch ? parseInt(otMatch[1], 10) : 10;",
    "      const basePay = payMatch ? parseInt(payMatch[1], 10) : fullDaily;",
    "      const regularHours = 8;",
    "      const otHours = Math.max(0, totalHours - regularHours);",
    "      const hourlyRate = Math.round(basePay / regularHours);",
    "      const otRate = Math.round(hourlyRate * 1.5);",
    "      const otAmount = otHours * otRate;",
    "      const totalPayout = basePay + otAmount;",
    "",
    "      if (lang === 'ta') {",
    "        reply = '💰 **கூடுதல் நேர ஊதியக் கணக்கீடு (' + totalHours + ' மணிநேரம்):**\\n\\n' +",
    "          '• அடிப்படை ஊதியம் (' + regularHours + ' மணி): **₹' + basePay + '** (₹' + hourlyRate + '/மணி)\\n' +",
    "          '• கூடுதல் நேரம் (' + otHours + ' மணி @ 1.5 மடங்கு): **₹' + otAmount + '** (₹' + otRate + '/மணி)\\n' +",
    "          '• 🎯 **மொத்த ஊதியம்**: **₹' + totalPayout + '**\\n\\n' +",
    "          '💡 *குறிப்பு: Talent2Task தளத்தில் கூடுதல் நேர வேலைகளுக்கு 1.5 மடங்கு ஊதியம் பரிந்துரைக்கப்படுகிறது.*';",
    "      } else if (lang === 'hi') {",
    "        reply = '💰 **ओवरटाइम मजदूरी गणना (' + totalHours + ' घंटे):**\\n\\n' +",
    "          '• मूल मजदूरी (' + regularHours + ' घंटे): **₹' + basePay + '** (₹' + hourlyRate + '/घंटा)\\n' +",
    "          '• ओवरटाइम (' + otHours + ' घंटे @ 1.5x): **₹' + otAmount + '** (₹' + otRate + '/घंटा)\\n' +",
    "          '• 🎯 **कुल देय राशि**: **₹' + totalPayout + '**\\n\\n' +",
    "          '💡 *सुझाव: Talent2Task पर ओवरटाइम के लिए 1.5 गुना मानक दर लागू होती है।*';",
    "      } else if (lang === 'te') {",
    "        reply = '💰 **ఓవర్‌టైమ్ వేతన లెక్క (' + totalHours + ' గంటలు):**\\n\\n' +",
    "          '• ప్రాథమిక వేతనం (' + regularHours + ' గంటలు): **₹' + basePay + '** (₹' + hourlyRate + '/గంట)\\n' +",
    "          '• ఓవర్‌టైమ్ (' + otHours + ' గంటలు @ 1.5x): **₹' + otAmount + '** (₹' + otRate + '/గంట)\\n' +",
    "          '• 🎯 **మొత్తం చెల్లింపు**: **₹' + totalPayout + '**';",
    "      } else {",
    "        reply = '💰 **Overtime Payout Calculation (' + totalHours + ' Hours Total):**\\n\\n' +",
    "          '• **Standard Base (' + regularHours + ' hrs)**: ₹' + basePay + ' (₹' + hourlyRate + '/hr)\\n' +",
    "          '• **Overtime (' + otHours + ' hrs @ 1.5x rate)**: ₹' + otAmount + ' (₹' + otRate + '/hr)\\n' +",
    "          '• 🎯 **Total Estimated Payout**: **₹' + totalPayout + '**\\n\\n' +",
    "          '💡 *Fair Work Standard: Overtime shifts on Talent2Task are benchmarked at 1.5x base hourly rate.*';",
    "      }",
    "    } else {",
    "      if (lang === 'ta') {",
    "        reply = '📊 **' + city + ' பகுதியில் ' + targetSkill + ' பணிக்கான சந்தை ஊதிய விவரம்:**\\n\\n' +",
    "          '• குறைந்தபட்ச ஊதியம் (அரை நாள் / 4 மணி): **₹' + baseDaily + '**\\n' +",
    "          '• சராசரி தினசரி ஊதியம் (8 மணி ஷிப்ட்): **₹' + fullDaily + '**\\n' +",
    "          '• அனுபவம் வாய்ந்த வல்லுநர் ஊதியம்: **₹' + masterDaily + '**\\n\\n' +",
    "          '💡 *வழிகாட்டுதல்: ₹' + fullDaily + '+ வழங்கும் வேலைகள் 15 நிமிடங்களில் தொழிலாளர்களால் ஏற்கப்படுகின்றன.*';",
    "      } else if (lang === 'hi') {",
    "        reply = '📊 **' + city + ' में ' + targetSkill + ' के लिए बाजार मजदूरी बेंचमार्क:**\\n\\n' +",
    "          '• न्यूनतम दर (आधा दिन / 4 घंटे): **₹' + baseDaily + '**\\n' +",
    "          '• मानक दैनिक मजदूरी (8 घंटे शिफ्ट): **₹' + fullDaily + '**\\n' +",
    "          '• अनुभवी कारीगर दर: **₹' + masterDaily + '**\\n\\n' +",
    "          '💡 *सुझाव: ₹' + fullDaily + '+ की पेशकश करने वाले कार्यों को श्रमिक जल्दी स्वीकार करते हैं।*';",
    "      } else if (lang === 'te') {",
    "        reply = '📊 **' + city + ' లో ' + targetSkill + ' కోసం మార్కెట్ వేతన వివరాలు:**\\n\\n' +",
    "          '• కనీస రేటు (సగం రోజు / 4 గంటలు): **₹' + baseDaily + '**\\n' +",
    "          '• ప్రామాణిక రోజువారీ వేతనం (8 గంటల షిఫ్ట్): **₹' + fullDaily + '**\\n' +",
    "          '• అనుభవజ్ఞులైన నిపుణుల రేటు: **₹' + masterDaily + '**';",
    "      } else {",
    "        reply = '📊 **Live Market Wage Benchmark for ' + targetSkill + ' in ' + city + ':**\\n\\n' +",
    "          '• **Minimum Base (Half Shift / 4h)**: ₹' + baseDaily + '\\n' +",
    "          '• **Standard Market Average (Full Day / 8h)**: **₹' + fullDaily + '** (₹' + avgHourly + '/hr)\\n' +",
    "          '• **Senior / Master Craftsperson**: ₹' + masterDaily + '\\n\\n' +",
    "          '💡 *Talent2Task Insights: Gigs benchmarked at ₹' + fullDaily + '+ receive worker claims 3.2x faster.*';",
    "      }",
    "",
    "      actions.push({",
    "        type: 'OPEN_POST_JOB',",
    "        label: lang === 'ta' ? ('₹' + fullDaily + ' ஊதியத்தில் வேலை வெளியிடு') : ('Post ' + targetSkill + ' Gig at ₹' + fullDaily),",
    "        payload: { category: targetSkill, payoutAmount: fullDaily, selectedCity: city }",
    "      });",
    "      actions.push({",
    "        type: 'OPEN_COMMUNITY_DEMAND',",
    "        label: lang === 'ta' ? 'தேவை வரைபடத்தைக் காண்க' : 'View District Demand Trends'",
    "      });",
    "    }",
    "",
    "    return {",
    "      id: 'msg_' + Date.now(),",
    "      sender: 'assistant',",
    "      text: reply,",
    "      timestamp,",
    "      actions,",
    "      intent: 'WAGE_QUERY'",
    "    };",
    "  }"
  ].join('\n');
  code = code.replace(methodInsertMarker, newMethods + '\n\n' + methodInsertMarker);
}

// 3. Make sure return block in extractEntities includes the new fields
if (!code.includes('navigationTarget,\n      isWageQueryIntent,')) {
  code = code.replace(
    '      isFollowUpFilter,\n      rawText: cleanText',
    '      isFollowUpFilter,\n      navigationTarget,\n      isWageQueryIntent,\n      isOvertimeQueryIntent,\n      rawText: cleanText'
  );
}

fs.writeFileSync('src/services/chatAssistantService.ts', code);
console.log('Patch successfully applied to chatAssistantService.ts!');
